version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/commons-asm"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/commons-brigadier"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/commons-netty"
    schedule:
      interval: "daily"
